export default {
  relatedUuid: {},
  selectedRepository: {
    uuid: 'e1e8a0fa-625c-4ba3-8b91-4c9f308db791',
    name: 'Binary Answers',
    slug: 'binary',
    description: 'Welcome for your first repository!',
    is_private: false,
    available_languages: [
      'pt_br',
      'nl',
      'ha',
      'es',
      'en',
    ],
    entities: [],
    entities_list: [],
    labels_list: [],
    ready_for_train: false,
    created_at: '2018-06-11T22:02:42.185098Z',
    language: 'pt_br',
    owner: 2,
    owner__nickname: 'johncordeiro',
    categories: [
      3,
    ],
    categories_list: [
      {
        id: 3,
        name: 'Configuration',
        icon: 'config',
      },
    ],
    intents: [
      {
        value: 'bias',
        examples__count: 43,
      },
      {
        value: 'doubt',
        examples__count: 46,
      },
      {
        value: 'negative',
        examples__count: 117,
      },
      {
        value: 'affirmative',
        examples__count: 158,
      },
    ],
    intents_list: [
      'bias',
      'doubt',
      'negative',
      'affirmative',
    ],
    labels: [],
    other_label: {
      repository: 'e1e8a0fa-625c-4ba3-8b91-4c9f308db791',
      value: 'other',
      entities: [],
      examples__count: 0,
    },
    examples__count: 364,
    evaluate_languages_count: {
      pt_br: 121,
      nl: 0,
      ha: 0,
      es: 0,
      en: 0,
    },
    absolute_url: 'https://bothub.it/johncordeiro/binary/',
    authorization: {
      uuid: '9c9db65c-b693-472e-b1c3-3c82eb7209fc',
      user: 30,
      user__nickname: 'Meneghini',
      repository: 'e1e8a0fa-625c-4ba3-8b91-4c9f308db791',
      role: 3,
      level: 3,
      can_read: true,
      can_contribute: true,
      can_write: true,
      is_admin: true,
      created_at: '2018-08-13T17:03:29.683448Z',
      id_request_authorizations: 49,
    },
    requirements_to_train: {},
    languages_ready_for_train: {
      pt_br: false,
      nl: false,
      ha: false,
      es: false,
      en: false,
    },
    request_authorization: {
      id: 49,
      user__nickname: 'Meneghini',
      repository: 'e1e8a0fa-625c-4ba3-8b91-4c9f308db791',
      text: 'Opa, aceita essa acc pf (:',
      approved_by: 18,
      approved_by__nickname: 'Tales',
      created_at: '2019-06-07T19:30:17.183696Z',
    },
    available_request_authorization: false,
    languages_warnings: {},
    algorithm: 'neural_network_internal',
    use_language_model_featurizer: false,
    use_competing_intents: false,
    use_name_entities: false,
    use_analyze_char: false,
    nlp_server: 'https://nlp.bothub.it/',
  },
  updateRepository: false,
  evaluateResultId: 0,
  evaluateResultVersion: 0,
  evaluateLanguage: '',
  currentTabSelected: 0,
};
